<?php
require_once __DIR__.'/includes/auth.php';
require_login();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent Management</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><h2>Agent Management</h2><a href="index.php" class="btn btn-outline-secondary">Dashboard</a></div><div class="alert alert-warning">Enrollment endpoints must be protected by the application RBAC layer. Never expose generated tokens in logs.</div><div class="card mb-4"><div class="card-body"><h5>Enroll Agent</h5><form id="enroll"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="agent_id" placeholder="SERVER-01" required></div><div class="col-md-4"><input class="form-control" name="host_name" placeholder="Production Server 01"></div><div class="col-md-4"><input class="form-control" name="hostname" placeholder="server01.example.local"></div></div><button class="btn btn-primary mt-3">Generate Token</button></form><pre id="result" class="mt-3 p-3 bg-dark text-light rounded d-none"></pre></div></div><div class="card"><div class="card-body"><h5>Registered Agents</h5><div class="table-responsive"><table class="table" id="agents"><thead><tr><th>Agent</th><th>Hostname</th><th>IP</th><th>OS</th><th>Version</th><th>Last Seen</th><th>Status</th></tr></thead><tbody></tbody></table></div></div></div></main><script>
const api=(p,o={})=>fetch(p,{headers:{'content-type':'application/json'},...o}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d});
async function load(){const rows=await api('/api/v1/agents');document.querySelector('#agents tbody').innerHTML=rows.map(a=>`<tr><td>${esc(a.agent_id)}</td><td>${esc(a.hostname||'')}</td><td>${esc(a.ip_address||'')}</td><td>${esc(a.os_name||'')}</td><td>${esc(a.agent_version||'')}</td><td>${esc(a.last_seen||'Never')}</td><td>${a.enabled?'Enabled':'Disabled'}</td></tr>`).join('')}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelector('#enroll').addEventListener('submit',async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));const out=document.querySelector('#result');try{const d=await api('/api/v1/admin/agents/enroll',{method:'POST',body:JSON.stringify(b)});out.classList.remove('d-none');out.textContent=`Agent: ${d.agentId}\nToken (save now): ${d.token}`;e.target.reset();load()}catch(err){out.classList.remove('d-none');out.textContent=err.message}});load();
</script></body></html>
