import Fastify from 'fastify';
import mysql from 'mysql2/promise';
import crypto from 'node:crypto';
const app=Fastify({logger:true});
const db=mysql.createPool({host:process.env.DB_HOST||'mysql',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'monitor',password:process.env.DB_PASSWORD||'monitor',database:process.env.DB_NAME||'monitoring',connectionLimit:10});
const sha=x=>crypto.createHash('sha256').update(x||'').digest('hex');
async function auth(req,reply){const v=req.headers.authorization||'';const token=v.startsWith('Bearer ')?v.slice(7):'';if(!token)return reply.code(401).send({error:'unauthorized'});const [r]=await db.execute('SELECT id,agent_id,enabled FROM agents WHERE token_hash=? LIMIT 1',[sha(token)]);if(!r.length||!r[0].enabled)return reply.code(401).send({error:'invalid agent token'});req.agent=r[0];}
app.get('/health',async()=>({ok:true,time:new Date().toISOString()}));
app.post('/api/v1/agent/report',{preHandler:auth},async(req)=>{const b=req.body||{},a=req.agent,now=new Date(b.timestamp||Date.now());await db.execute('UPDATE agents SET hostname=?,ip_address=?,os_name=?,os_release=?,agent_version=?,last_seen=NOW() WHERE id=?',[b.system?.hostname||null,b.system?.ip_lan?.[0]||null,b.system?.os||null,b.system?.os_release||null,b.agent_version||null,a.id]);const [h]=await db.execute('SELECT id FROM hosts WHERE agent_id=? LIMIT 1',[a.id]);let hid=h[0]?.id;if(!hid){const [r]=await db.execute('INSERT INTO hosts(agent_id,name,hostname,status,last_seen) VALUES(?,?,?,"ONLINE",NOW())',[a.id,b.system?.hostname||a.agent_id,b.system?.hostname||a.agent_id]);hid=r.insertId}else await db.execute('UPDATE hosts SET status="ONLINE",last_seen=NOW(),hostname=? WHERE id=?',[b.system?.hostname||null,hid]);const rows=(b.metrics||[]).map(m=>[hid,m.key,JSON.stringify(m.value),now]);(b.disks||[]).forEach(d=>rows.push([hid,`disk.used[${d.mount}]`,JSON.stringify(d.use_percent),now]));if(rows.length)await db.query('INSERT INTO metrics(host_id,metric_key,metric_value,recorded_at) VALUES ?',[rows]);for(const c of b.checks||[])await db.execute('INSERT INTO check_results(host_id,check_type,target,ok,response_ms,status_code,error_message,checked_at) VALUES(?,?,?,?,?,?,?,NOW())',[hid,c.type,c.target,c.ok?1:0,c.ms||null,c.status||null,c.error||null]);return{success:true,host_id:hid}});
app.get('/api/v1/dashboard/summary',async()=>{const [[h]]=await db.query('SELECT COUNT(*) total,SUM(status="ONLINE") online,SUM(status="WARNING") warning,SUM(status="CRITICAL") critical,SUM(status="OFFLINE") offline FROM hosts');const [[a]]=await db.query('SELECT COUNT(*) open_alerts FROM alerts WHERE status IN ("OPEN","ACKNOWLEDGED")');return{hosts:h,alerts:a}});
app.get('/api/v1/hosts',async()=>{const[r]=await db.query('SELECT h.*,a.agent_id,a.last_seen agent_last_seen FROM hosts h LEFT JOIN agents a ON a.id=h.agent_id ORDER BY h.name');return r});
app.get('/api/v1/hosts/:id/metrics',async req=>{const[r]=await db.execute('SELECT metric_key,metric_value,recorded_at FROM metrics WHERE host_id=? ORDER BY recorded_at DESC LIMIT 500',[req.params.id]);return r});
app.get('/api/v1/alerts',async()=>{const[r]=await db.query('SELECT al.*,h.name host_name FROM alerts al JOIN hosts h ON h.id=al.host_id ORDER BY al.created_at DESC LIMIT 500');return r});
app.setErrorHandler((e,req,reply)=>{req.log.error(e);reply.code(500).send({error:'internal_error'})});
app.listen({port:Number(process.env.PORT||3000),host:process.env.HOST||'0.0.0.0'}).catch(e=>{app.log.error(e);process.exit(1)});
