CREATE DATABASE IF NOT EXISTS monitoring CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE monitoring;

CREATE TABLE IF NOT EXISTS agents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agent_id VARCHAR(128) NOT NULL UNIQUE, token_hash CHAR(64) NOT NULL UNIQUE, enabled TINYINT(1) NOT NULL DEFAULT 1,
 hostname VARCHAR(255), ip_address VARCHAR(64), os_name VARCHAR(128), os_release VARCHAR(128), agent_version VARCHAR(32), last_seen DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_agents_last_seen(last_seen)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS hosts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agent_id BIGINT UNSIGNED NULL, name VARCHAR(255) NOT NULL, hostname VARCHAR(255), status ENUM('ONLINE','WARNING','CRITICAL','OFFLINE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN', last_seen DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_host_agent(agent_id), INDEX idx_hosts_status(status), INDEX idx_hosts_last_seen(last_seen), CONSTRAINT fk_hosts_agent FOREIGN KEY(agent_id) REFERENCES agents(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS metrics (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, host_id BIGINT UNSIGNED NOT NULL, metric_key VARCHAR(255) NOT NULL, metric_value JSON NOT NULL, recorded_at DATETIME(3) NOT NULL,
 INDEX idx_metrics_host_key_time(host_id,metric_key,recorded_at), INDEX idx_metrics_time(recorded_at), CONSTRAINT fk_metrics_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS check_results (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, host_id BIGINT UNSIGNED NOT NULL, check_type VARCHAR(32) NOT NULL, target VARCHAR(1024) NOT NULL, ok TINYINT(1) NOT NULL, response_ms DECIMAL(12,3), status_code INT, error_message TEXT, checked_at DATETIME NOT NULL,
 INDEX idx_checks_host_time(host_id,checked_at), INDEX idx_checks_target(target(191)), CONSTRAINT fk_checks_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS monitor_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, host_id BIGINT UNSIGNED NOT NULL, item_key VARCHAR(255) NOT NULL, item_type VARCHAR(64) NOT NULL DEFAULT 'metric', enabled TINYINT(1) NOT NULL DEFAULT 1, interval_sec INT NOT NULL DEFAULT 60, config JSON NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_item(host_id,item_key), CONSTRAINT fk_items_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alert_rules (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, metric_key VARCHAR(255) NOT NULL, operator ENUM('>','>=','<','<=','=','!=') NOT NULL, threshold DECIMAL(20,6) NULL,
 severity ENUM('INFO','WARNING','HIGH','CRITICAL') NOT NULL DEFAULT 'WARNING', duration_sec INT NOT NULL DEFAULT 0, enabled TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alert_rule_states (
 host_id BIGINT UNSIGNED NOT NULL, rule_id BIGINT UNSIGNED NOT NULL, first_bad_at DATETIME(3) NULL, last_value DECIMAL(30,10) NULL, updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY(host_id,rule_id), CONSTRAINT fk_state_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE, CONSTRAINT fk_state_rule FOREIGN KEY(rule_id) REFERENCES alert_rules(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alerts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, host_id BIGINT UNSIGNED NOT NULL, rule_id BIGINT UNSIGNED NULL, fingerprint CHAR(64) NOT NULL, severity ENUM('INFO','WARNING','HIGH','CRITICAL') NOT NULL,
 status ENUM('OPEN','ACKNOWLEDGED','RESOLVED') NOT NULL DEFAULT 'OPEN', title VARCHAR(255) NOT NULL, message TEXT, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at DATETIME NULL, acknowledged_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_alert_fingerprint_status(fingerprint,status), INDEX idx_alert_status(status), INDEX idx_alert_host(host_id), CONSTRAINT fk_alert_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE, CONSTRAINT fk_alert_rule FOREIGN KEY(rule_id) REFERENCES alert_rules(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alert_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, alert_id BIGINT UNSIGNED NOT NULL, event_type VARCHAR(32) NOT NULL, message TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_alert_events(alert_id,created_at), CONSTRAINT fk_alert_events FOREIGN KEY(alert_id) REFERENCES alerts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notification_channels (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, type ENUM('TELEGRAM','EMAIL','WEBHOOK') NOT NULL, config JSON NOT NULL, enabled TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alert_notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, alert_id BIGINT UNSIGNED NOT NULL, channel_id BIGINT UNSIGNED NOT NULL, status ENUM('PENDING','SENT','FAILED') NOT NULL DEFAULT 'PENDING', attempts INT NOT NULL DEFAULT 0, last_error TEXT, sent_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_notification_status(status), CONSTRAINT fk_an_alert FOREIGN KEY(alert_id) REFERENCES alerts(id) ON DELETE CASCADE, CONSTRAINT fk_an_channel FOREIGN KEY(channel_id) REFERENCES notification_channels(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS maintenance_windows (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, host_id BIGINT UNSIGNED NULL, name VARCHAR(255) NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, enabled TINYINT(1) NOT NULL DEFAULT 1, INDEX idx_maintenance_time(starts_at,ends_at), CONSTRAINT fk_maint_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS dependencies (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, parent_host_id BIGINT UNSIGNED NOT NULL, child_host_id BIGINT UNSIGNED NOT NULL, enabled TINYINT(1) NOT NULL DEFAULT 1, UNIQUE KEY uq_dependency(parent_host_id,child_host_id), CONSTRAINT fk_dep_parent FOREIGN KEY(parent_host_id) REFERENCES hosts(id) ON DELETE CASCADE, CONSTRAINT fk_dep_child FOREIGN KEY(child_host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(128) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('ADMIN','OPERATOR','VIEWER') NOT NULL DEFAULT 'VIEWER', enabled TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(128) NOT NULL, entity VARCHAR(128), entity_id BIGINT UNSIGNED NULL, ip_address VARCHAR(64), details JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_time(created_at), CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
