USE monitoring;
CREATE TABLE IF NOT EXISTS alert_rule_states (
 host_id BIGINT UNSIGNED NOT NULL,
 rule_id BIGINT UNSIGNED NOT NULL,
 first_bad_at DATETIME(3) NULL,
 last_value DECIMAL(30,10) NULL,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY(host_id,rule_id),
 CONSTRAINT fk_state_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE,
 CONSTRAINT fk_state_rule FOREIGN KEY(rule_id) REFERENCES alert_rules(id) ON DELETE CASCADE
) ENGINE=InnoDB;
