USE monitoring;
CREATE TABLE IF NOT EXISTS host_daily_availability (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  host_id BIGINT UNSIGNED NOT NULL,
  day DATE NOT NULL,
  up_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  down_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  unknown_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  availability_pct DECIMAL(8,4) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_host_day(host_id,day),
  INDEX idx_availability_day(day),
  CONSTRAINT fk_availability_host FOREIGN KEY(host_id) REFERENCES hosts(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sla_targets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  target_pct DECIMAL(8,4) NOT NULL DEFAULT 99.9000,
  period_days INT NOT NULL DEFAULT 30,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
